### ISSUE TITLE
Alternative splicing (AS) events combination

### ISSUE THREAD

**Issue by OlgaVT** [ed-lau/jcast#12]
Hi!

I might probably miss it in the publications: do you take into account the combination of AS events? Let say if there are two skipped exons in one gene - does jcast generate possible isoforms from these two events independently or also with both exons skipped?

Thank you!

**Comment by ed-lau** [comment]
Hi, currently JCAST only looks at individual junctions and doesn't handle combinatorial isoforms.

**Comment by OlgaVT** [comment]
Thank you for the quick reply!
