### ISSUE TITLE
Pvalue filtering

### ISSUE THREAD

**Issue by OlgaVT** [ed-lau/jcast#13]
Hi,

I wondered why you filter out the significant events but later found an answer in the publication.

And in the pip version the filtering is by fdr not pvalue as stated in the help description - but is it not an issue.

**Comment by ed-lau** [comment]
Hi, the original intent was to translate only consistent junctions and remove significantly different junctions between samples. If you download the current version from GitHub, you will be able to define a range of FDR to include (-q lo hi).
