### ISSUE TITLE
Parallel execution of JCAST

### ISSUE THREAD

**Issue by n-hackert** [ed-lau/jcast#14]
Hey,

first of all I'd like to thank you for developing and maintaining this great tool! I was wondering whatever happened to the option to execute JCAST in parallel that is currently commented out in the main.py file (I could trace it back to this commit: https://github.com/ed-lau/jcast/commit/0ab7abb0368311e54a2ae49f3619a26e38c498ae). Personally I think, my running times would greatly benefit, if it were possible to distribute the translation steps over multiple threads. However, before trying to re-implement multithreading myself, I just wanted to make sure I am not missing anything or if there is a specific reason for you disabling this option. Thanks in advance, and sorry if there is an obvious answer to my question that I might have missed!

Best,
Nico

**Comment by ed-lau** [comment]
Thanks for the note. The multithreading doesn't play well with the progress bar, but you should be able to re-enable it.

**Comment by n-hackert** [comment]
Thank you so much for your quick reply!
