### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by wexlerjin** [ed-lau/jcast#17]
Hello，
First of all, thank you for your jcast. The tools you developed helped me a lot. But i still have some problems in output file. You only mentioned T1.fasta in article(Determining Alternative Protein Isoform Expression Using RNA Sequencing and Mass Spectrometry). Is it means that T1.fasta is the final input fasta file for maxquant in your anaylsis process?  or you organized other files(T2/T3/T4) into one file because the possibility of translation of peptides in other files(T2/T3/T4). Thanks for your time.

Best, Wex.

**Comment by ed-lau** [comment]
For a typical application, I would recommend appending T1.fasta to either the JCAST canonical output (which writes the canonical sequence for any gene that has been detected above the read count cutoff, regardless of whether the non-canonical translation was successful), or to a Uniprot canonical database. The lower tier fasta files contain sequences with frame shifts and/or termination codons. You can include them by appending them to the T1+canonical fasta, but the results should be interpreted with caution.

**Comment by wexlerjin** [comment]
Hi Ed,

Thanks for the quick response and the detailed explanation.


Best,
wex
