### ISSUE TITLE
Is it possible to run jcast with species other than human and mouse?

### ISSUE THREAD

**Issue by rpm78** [ed-lau/jcast#2]
Are there hard-coded calls to human or  mouse databases in jcast?  
If I pointed it to, say, rat genome and gtf files at the command line would that work?

Thanks for making jcast available.

rpm

**Comment by ed-lau** [comment]
We have a new version that should work with rat or any species in theory (provided genome file). Will update the documentation and put on this repo.

**Comment by ed-lau** [comment]
Current version should work with a provided genome fasta (e.g., Homo_sapiens.GRCh38.dna.primary_assembly.fa from Ensembl). It will require enough memory to load the genome in memory. Feel free to let us know if it works with the rat files and thanks.

**Comment by rpm78** [comment]
Found two issues.
Thanks for putting up your code.

Ray

**Comment by ed-lau** [comment]
Thanks! Will look into them ...
