### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by xpgege** [ed-lau/jcast#5]
Hello，I get a Key error like this .
![image](https://user-images.githubusercontent.com/49704025/87385581-01f6a700-c5d1-11ea-8d82-51d109665e5e.png)
Compared with your example gtf file.
I think it's because of the gtf version problem .
Could you tell me which gtf file should I choose?

**Comment by ed-lau** [comment]
Human, mouse, and rat GTF from Ensembl  http://uswest.ensembl.org/info/data/ftp/index.html 
Can you point me to the GTF file you use so I can look into the issue? Thanks

**Comment by xpgege** [comment]
Thanks for your reply!
Firstly,I  tried Gencode hg19.gtf ，so I got this ccds_id keyerror problem
Then I tried Homo_sapiens.GRCh37.87.chr.gtf.gz.
I got the Key error:"transcript_support_level"
It seems that this kind of gtf don't have the key word "transcript_support_level"

**Comment by ed-lau** [comment]
Got it thanks ... I will grab the Gencode annotations and look into the issue. In the mean time have you tried the Github version rather than install from PyPI? We recently added a quick bypass for transcript support/ccds_id after it was pointed out that those tags aren't annotated in organisms other than human/mouse on Ensembl.

**Comment by xpgege** [comment]
Oh! I have tried the github version Jcast-0.2.3 yesterday.
1. I substitute the hg19.gtf  ccdsid->ccds_id
2. I substitute the hg19.fa  like this :" >chr10"  ->   ">10" 
However  I got an error like this:
![image](https://user-images.githubusercontent.com/49704025/87635113-212c3a80-c771-11ea-917a-cbf76555af77.png)
then I  change the code here:
![image](https://user-images.githubusercontent.com/49704025/87635265-56388d00-c771-11ea-9244-bb947ce71022.png)
Finally I can work out the result through the jcast-0.2.3  and genecode hg19.
I don't kown whether I'm correct for change the code.
Thanks for your help!

**Comment by xpgege** [comment]
Oh! I have tried the github version Jcast-0.2.3 yesterday.

I substitute the hg19.gtf ccdsid->ccds_id
I substitute the hg19.fa like this :" >chr10" -> ">10"
However I got an error like this:
![image](https://user-images.githubusercontent.com/49704025/87635605-ee367680-c771-11ea-92ab-40713456f4d4.png)
then I change the code here:
![image](https://user-images.githubusercontent.com/49704025/87635780-38b7f300-c772-11ea-9536-3b43b343e0d9.png)
Finally I can work out the result through the jcast-0.2.3 and genecode hg19.
I don't kown whether I'm right for change the code.
Thanks for your help!

**Comment by xpgege** [comment]
Oh! I have tried the github version Jcast-0.2.3 yesterday.

I substitute the hg19.gtf ccdsid->ccds_id
I substitute the hg19.fa like this :" >chr10" -> ">10"
However I got an error like this:
![image](https://user-images.githubusercontent.com/49704025/87635893-613fed00-c772-11ea-888b-f08cdc011ce5.png)

then I change the code here:
![image](https://user-images.githubusercontent.com/49704025/87635930-73219000-c772-11ea-8872-b5119a5ee50d.png)

Finally I can work out the result through the jcast-0.2.3 and genecode hg19.
I don't kown whether I'm right for change the code.
Thanks for your help!

**Comment by xpgege** [comment]
I think I don't get the right result...sorry,maybe it's the network problem
![image](https://user-images.githubusercontent.com/49704025/87637632-1c698580-c775-11ea-9bf6-37c3aaf42fe6.png)

**Comment by xpgege** [comment]
Thanks for your reply！
I successfully get the result with the github version jcast-0.2.3！
Howerer,I get the files like this：
![image](https://user-images.githubusercontent.com/49704025/87681696-83a52b00-c7b1-11ea-8234-b06f150aa134.png)
I wonder what's the meaning of these fasta files

**Comment by ed-lau** [comment]
Hi - briefly: 

T1: non-canonical junction slices translated completely without any stop codons. 
T2: same as T1 but one of the slices has a frameshift.
T3: same as T1 but using a different frame than read from the GTF. 
T4: one of the slices had a stop codon in all tried frames; using the frame with the longest slice if the translated slice with stop codon is at least half the length of the other slice prior to stop.
Orphans: translated junctions that couldn't be stitched back to the Swissprot entry using a 10-aa joint (no full length proteins in these fastas, only fragments). 
Canonical: a translated slice that is identical the SwissProt entry (canonical gene product).
Gene_Canoncial: none of the transcript junctions from this gene can be translated successfully but assuming this gene is represented in the RNA-seq data, we put the canonical sequence here for reference.


Depending on your usage, you can start a search by combining T1 with canonical, or appending T1 to the full SwissProt, and go from there depending on whether you want to let in the lower-tier slices. Feel free to refer to our publications (PMID: 31825849) for other details.
