### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by malbahrani** [ed-lau/jcast#6]
Hi,

In the README file, you mentioned how to [prepare the inputs for rMATS](https://github.com/ed-lau/jcast#prepare-the-rmats-subdirectory).  Should not be only one `.bam` file per a pair of aligned FASTQ files after running STAR?  

Thanks,

**Comment by ed-lau** [comment]
Hello,
There should be one bam file per paired of aligned PE reads. rMATS analyzes the aligned bam files from at least 2 replicate samples in order to compare splice in level. JCAST uses the result to discard low-read and inconsistent junctions.
